name: app_controller
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  core:
    path: ../../core
  core_tdlib_api:
    path: ../../core_tdlib_api
  device_info_plus: 3.2.2
  path_provider: 2.0.9
  rxdart: 0.27.3

dev_dependencies:
  build_runner: 2.1.7
  mockito: 5.1.0
  test: 1.20.1
  test_utils:
    path: ../../test_utils
  tg_lint_rules:
    path: ../../tg_lint_rules