name: app_controller
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  core:
    path: ../../core
  core_tdlib_api:
    path: ../../core_tdlib_api
  device_info_plus: 3.2.2
  path_provider: 2.0.9
  rxdart: 0.27.3
  td_api:
    path: ../../td/td_api

dev_dependencies:
  build_runner: 2.3.2
  dependency_validator: 3.2.0
  mockito: 5.3.2
  test: 1.22.0
  test_utils:
    path: ../../test_utils
  tg_lint_rules:
    path: ../../tg_lint_rules