name: core_presentation
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  core:
    path: ../core
  core_utils:
    path: ../core_utils
  freezed_annotation: 2.1.0
  shared_models:
    path: ../shared/models
  td_api:
    path: ../td/td_api

dev_dependencies:
  build_runner: 2.2.0
  dependency_validator: 3.2.0
  freezed: 2.1.0+1
  tg_lint_rules:
    path: ../tg_lint_rules