name: chat_list_theme
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  tg_theme:
    path: ../../theme/tg_theme

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../../tg_lint_rules