name: feature_shared_media_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  feature_shared_media_api:
    path: ../feature_shared_media_api
  flutter:
    sdk: flutter
  jugger: 2.1.0
  localization_api:
    path: ../../localization_api
  provider_extensions:
    path: ../../provider_extensions

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  jugger_generator: 2.2.1
  tg_lint_rules:
    path: ../../tg_lint_rules

flutter: