name: feature_dev
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  flutter:
    sdk: flutter
  jugger: ^2.0.0
  rxdart: ^0.26.0
  showcase:
    path: ../../showcase
  td_client:
    path: ../../td_client

dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.1.2
  jugger_generator: ^2.0.0
  tg_lint_rules:
    path: ../../tg_lint_rules