name: feature_dev
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  dialog_api:
    path: ../../dialog_api
  feature_country_api:
    path: ../feature_country_api
  flutter:
    sdk: flutter
  jugger: 2.3.1
  localization_api:
    path: ../../localization_api
  rxdart: 0.27.3
  scrollable_positioned_list: 0.3.2
  showcase:
    path: ../../showcase
  td_api:
    path: ../../td/td_api
  theme_manager_api:
    path: ../theme/theme_manager_api

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  jugger_generator: 2.5.1
  tg_lint_rules:
    path: ../../tg_lint_rules