name: feature_dev
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  dialog_api:
    path: ../../dialog_api
  feature_country_api:
    path: ../feature_country_api
  flutter:
    sdk: flutter
  jugger: 2.1.0
  rxdart: 0.27.3
  showcase:
    path: ../../showcase
  td_client:
    path: ../../td_client

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  jugger_generator: 2.2.1
  tg_lint_rules:
    path: ../../tg_lint_rules