name: feature_main_screen_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_arch:
    path: ../../core_arch
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  feature_chats_list_api:
    path: ../feature_chats_list_api
  feature_global_search_api:
    path: ../feature_global_search_api
  feature_main_screen_api:
    path: ../feature_main_screen_api
  flutter:
    sdk: flutter
  jugger:
     git:
       url: git@github.com:ivk1800/jugger.dart.git
       path: jugger
       ref: 85d05caacbe81d3a683c1d31a9b27735e512bb93
  localization_api:
    path: ../../localization_api
  provider: ^6.0.0
  provider_extensions:
    path: ../../provider_extensions
  td_client:
    path: ../../td_client

dev_dependencies:
  build_runner: 2.1.1
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: c1db629af1108851234014cb98eeb135f3673315
  tg_lint_rules:
    path: ../../tg_lint_rules