name: feature_global_search_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  chat_router_api:
    path: ../chat/chat_router_api
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  feature_global_search_api:
    path: ../feature_global_search_api
  flutter:
    sdk: flutter
  freezed_annotation: 1.1.0
  localization_api:
    path: ../../localization_api
  provider: 6.0.2
  provider_extensions:
    path: ../../provider_extensions
  rxdart: 0.27.3
  search_component:
    path: ../../search_component
  td_client:
    path: ../../td_client
  tile:
    path: ../../tile

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.1.2
  freezed: 1.1.1
  jugger_generator: 2.0.0
  tg_lint_rules:
    path: ../../tg_lint_rules