name: feature_global_search_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  chat_navigation_api:
    path: ../chat/chat_navigation_api
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  feature_global_search_api:
    path: ../feature_global_search_api
  flutter:
    sdk: flutter
  freezed_annotation: 1.1.0
  localization_api:
    path: ../../localization_api
  rxdart: 0.27.3
  search_component:
    path: ../../search_component
  td_client:
    path: ../../td_client
  tile:
    path: ../../tile

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  freezed: 1.1.1
  jugger_generator: 2.2.1
  tg_lint_rules:
    path: ../../tg_lint_rules