name: feature_global_search_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  chat_navigation_api:
    path: ../chat/chat_navigation_api
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  core_utils:
    path: ../../core_utils
  coreui:
    path: ../../coreui
  feature_file_api:
    path: ../feature_file_api
  feature_global_search_api:
    path: ../feature_global_search_api
  flutter:
    sdk: flutter
  freezed_annotation: 2.1.0
  jugger: 3.0.0
  localization_api:
    path: ../../localization_api
  rxdart: 0.27.3
  search_component:
    path: ../../search_component
  shared_models:
    path: ../../shared/models
  td_api:
    path: ../../td/td_api
  tile:
    path: ../../tile

dev_dependencies:
  build_runner: 2.2.0
  dependency_validator: 3.2.0
  freezed: 2.1.0+1
  jugger_generator: 3.0.0
  tg_lint_rules:
    path: ../../tg_lint_rules