name: scope_generator
homepage: https://github.com/ivk1800/jugger.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: 3.4.1
  build: 2.2.1
  code_builder: 4.1.0
  scope_generator_annotation:
    path: ../scope_generator_annotation
  source_gen: 1.2.1

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../tg_lint_rules