name: feature_create_new_chat_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  async_utils:
    path: ../../async_utils
  block_interaction_api:
    path: ../../block_interaction_api
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  dialog_api:
    path: ../../dialog_api
  error_transformer_api:
    path: ../../error_transformer_api
  feature_chat_api:
    path: ../feature_chat_api
  feature_create_new_chat_api:
    path: ../feature_create_new_chat_api
  flutter:
    sdk: flutter
  jugger: 2.1.0
  localization_api:
    path: ../../localization_api
  provider: 6.0.2
  provider_extensions:
    path: ../../provider_extensions

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  jugger_generator: 2.2.1
  tg_lint_rules:
    path: ../../tg_lint_rules