name: create_new_chat_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  feature_create_new_chat_api:
    path: ../feature_create_new_chat_api
  flutter:
    sdk: flutter

dev_dependencies:
  dependency_validator: ^3.1.2
  tg_lint_rules:
    path: ../../tg_lint_rules