name: core_arch
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  async: 2.8.2
  async_utils:
    path: ../async_utils

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../tg_lint_rules