name: feature_wallpappers_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  get: 4.1.4
  flutter_staggered_grid_view: ^0.4.0
  core_arch:
    path: ../../core_arch
  core_tdlib_api:
    path: ../../core_tdlib_api
  localization_api:
    path: ../../localization_api
  feature_wallpappers_api:
    path: ../feature_wallpappers_api
  coreui:
    path: ../../coreui
  flutter:
    sdk: flutter

flutter: