name: feature_stickers_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  async: 2.8.2
  async_utils:
    path: ../../async_utils
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  feature_stickers_api:
    path: ../feature_stickers_api
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  freezed_annotation: 2.1.0
  localization_api:
    path: ../../localization_api
  provider: 6.0.2
  rxdart: 0.27.3
  td_api:
    path: ../../td/td_api
  tile:
    path: ../../tile

dev_dependencies:
  build_runner: 2.2.0
  dependency_validator: 3.2.0
  freezed: 2.1.0+1
  tg_lint_rules:
    path: ../../tg_lint_rules