name: feature_new_contact_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  async_utils:
    path: ../../../../async_utils
  block_interaction_api:
    path: ../../../../block_interaction_api
  chat_navigation_api:
    path: ../../../chat/chat_navigation_api
  contacts_manager_api:
    path: ../../../contact/contacts_manager/contacts_manager_api
  core_arch:
    path: ../../../../core_arch
  core_arch_flutter:
    path: ../../../../core_arch_flutter
  core_tdlib_api:
    path: ../../../../core_tdlib_api
  coreui:
    path: ../../../../coreui
  dialog_api:
    path: ../../../../dialog_api
  error_transformer_api:
    path: ../../../../error_transformer_api
  feature_new_contact_api:
    path: ../feature_new_contact_api
  flutter:
    sdk: flutter
  freezed_annotation: 1.1.0
  jugger: 2.1.0
  localization_api:
    path: ../../../../localization_api
  provider_extensions:
    path: ../../../../provider_extensions
  rxdart: 0.27.3
  user_info:
    path: ../../../user/user_info

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  freezed: 1.1.1
  jugger_generator: 2.2.1
  tg_lint_rules:
    path: ../../../../tg_lint_rules