name: core_ui_jugger
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  core_tdlib_api:
    path: ../core_tdlib_api
  coreui:
    path: ../coreui
  flutter:
    sdk: flutter
  jugger: 3.0.0

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  jugger_generator: 3.0.0
  tg_lint_rules:
    path: ../tg_lint_rules