name: feature_folders_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  core_arch:
    path: ../../../core_arch
  core_tdlib_api:
    path: ../../../core_tdlib_api
  coreui:
    path: ../../../coreui
  dialog_api:
    path: ../../../dialog_api
  feature_folders_api:
    path: ../feature_folders_api
  flutter:
    sdk: flutter
  jugger: 2.2.0
  localization_api:
    path: ../../../localization_api

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  jugger_generator: 2.4.0
  tg_lint_rules:
    path: ../../../tg_lint_rules