name: feature_folders_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_arch:
    path: ../../../core_arch
  core_arch_flutter:
    path: ../../../core_arch_flutter
  core_tdlib_api:
    path: ../../../core_tdlib_api
  coreui:
    path: ../../../coreui
  feature_folders_api:
    path: ../feature_folders_api
  flutter:
    sdk: flutter
  folders_presentation:
    path: ../folders_presentation
  folders_ui_common:
    path: ../folders_ui_common
  jugger: 2.0.0
  localization_api:
    path: ../../../localization_api
  provider_extensions:
    path: ../../../provider_extensions

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.1.2
  jugger_generator: 2.1.0
  tg_lint_rules:
    path: ../../../tg_lint_rules