name: core_utils
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  core_tdlib_api:
    path: ../core_tdlib_api
  flutter:
    sdk: flutter
  intl: 0.17.0
  shared_models:
    path: ../shared/models

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../tg_lint_rules