name: feature_logout_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_tdlib_api:
    path: ../../core_tdlib_api
  feature_auth_api:
    path: ../feature_auth_api
  feature_logout_api:
    path: ../feature_logout_api
  dialog_api:
    path: ../../dialog_api
  coreui:
    path: ../../coreui
  localization_api:
    path: ../../localization_api
  equatable: ^2.0.0
  flutter_bloc: 7.2.0
  flutter:
    sdk: flutter
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 02cb9197b758cd89457d71c2b4c1daab4d92477c

dev_dependencies:
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: 2351119ad514db2c2ffbe286677e91936c39ee61
  build_runner: 2.1.1