name: coreui
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_tdlib_api:
    path: ../core_tdlib_api
  core_utils:
    path: ../core_utils
  feature_file_api:
    path: ../feature/feature_file_api
  flutter:
    sdk: flutter

dev_dependencies:
  dependency_validator: 3.1.2
  tg_lint_rules:
    path: ../tg_lint_rules

flutter:
  assets:
    - assets/icon/