name: coreui
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  core_tdlib_api:
    path: ../core_tdlib_api
  feature_file_api:
    path: ../feature/feature_file_api
  flutter:
    sdk: flutter
  freezed_annotation: 1.1.0
  lottie: 1.3.0
  rxdart: 0.27.3
  shared_models:
    path: ../shared/models
  td_api:
    path: ../td/td_api

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  freezed: 1.1.1
  tg_lint_rules:
    path: ../tg_lint_rules

flutter:
  assets:
    - assets/icon/