name: presentation
description: A new Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  dart_numerics: ^0.0.5
  rxdart: ^0.26.0
  core:
    path: ../core
  path_provider: ^2.0.1
  jugger: ^1.1.0-alpha
  td_client:
    path: ../td_client
  flutter:
    sdk: flutter

dev_dependencies:
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: c498a0031f463a4877cc4c65015ebad52e896ae0
  analyzer: ^1.1.0
  build_runner: ^1.10.2
  flutter_test:
    sdk: flutter

flutter: