name: presentation
description: A new Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  rxdart: ^0.26.0
  core:
    path: ../core
  path_provider: ^2.0.1
  jugger: ^1.1.0-alpha
  td_client:
    path: ../td_client
  flutter:
    sdk: flutter

dev_dependencies:
  jugger_generator: 1.1.0+4-alpha
  analyzer: ^1.1.0
  build_runner: ^1.10.2
  flutter_test:
    sdk: flutter

flutter: