name: td_rich_text_parser
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  rich_text_format:
    path: ../rich_text_format
  td_client:
    path: ../../td_client

dev_dependencies:
  test: 1.20.1
  tg_lint_rules:
    path: ../../tg_lint_rules