name: core_arch_flutter
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_arch:
    path: ../core_arch
  flutter:
    sdk: flutter
  provider: 6.0.0

dev_dependencies:
  tg_lint_rules:
    path: ../tg_lint_rules