name: core
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity: 3.0.6
  core_arch:
    path: ../core_arch
  core_tdlib_api:
    path: ../core_tdlib_api
  dependency_validator: ^3.1.2
  flutter:
    sdk: flutter
  intl: ^0.17.0
  rxdart: ^0.26.0
  td_client:
    path: ../td_client

dev_dependencies:
  tg_lint_rules:
    path: ../tg_lint_rules