name: core
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  connectivity_plus: 2.2.1
  core_arch:
    path: ../core_arch
  core_tdlib_api:
    path: ../core_tdlib_api
  flutter:
    sdk: flutter
  intl: 0.17.0
  rxdart: 0.27.3
  td_client:
    path: ../td_client

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../tg_lint_rules