name: core
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  jugger: ^1.1.0-alpha
  rxdart: ^0.26.0
  td_client:
    path: ../td_client
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: