name: theme_manager_flutter
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  tg_lint_rules:
    path: ../../../tg_lint_rules
  theme_manager_api:
    path: ../theme_manager_api