name: theme_manager_flutter
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  rxdart: 0.27.3
  tg_theme:
    path: ../../../feature/theme/tg_theme
  theme_manager_api:
    path: ../theme_manager_api

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../../tg_lint_rules