name: app
description: A new Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  chat_theme:
    path: ../feature/chat/chat_theme
  core:
    path: ../core
  core_tdlib_api:
    path: ../core_tdlib_api
  core_tdlib_impl:
    path: ../core_tdlib_impl
  core_utils:
    path: ../core_utils
  coreui:
    path: ../coreui
  dialog_api:
    path: ../dialog_api
  feature_auth_api:
    path: ../feature/feature_auth_api
  feature_auth_impl:
    path: ../feature/feature_auth_impl
  feature_chat_api:
    path: ../feature/feature_chat_api
  feature_chat_header_info_api:
    path: ../feature/feature_chat_header_info_api
  feature_chat_header_info_impl:
    path: ../feature/feature_chat_header_info_impl
  feature_chat_impl:
    path: ../feature/feature_chat_impl
  feature_chat_settings_api:
    path: ../feature/feature_chat_settings_api
  feature_chat_settings_impl:
    path: ../feature/feature_chat_settings_impl
  feature_chats_list_api:
    path: ../feature/feature_chats_list_api
  feature_chats_list_impl:
    path: ../feature/feature_chats_list_impl
  feature_country_api:
    path: ../feature/feature_country_api
  feature_country_impl:
    path: ../feature/feature_country_impl
  feature_data_settings_api:
    path: ../feature/feature_data_settings_api
  feature_data_settings_impl:
    path: ../feature/feature_data_settings_impl
  feature_dev:
    path: ../feature/feature_dev
  feature_file_api:
    path: ../feature/feature_file_api
  feature_file_impl:
    path: ../feature/feature_file_impl
  feature_folders_api:
    path: ../feature/folders/feature_folders_api
  feature_folders_impl:
    path: ../feature/folders/feature_folders_impl
  feature_global_search_api:
    path: ../feature/feature_global_search_api
  feature_global_search_impl:
    path: ../feature/feature_global_search_impl
  feature_logout_api:
    path: ../feature/feature_logout_api
  feature_logout_impl:
    path: ../feature/feature_logout_impl
  feature_main_screen_api:
    path: ../feature/feature_main_screen_api
  feature_main_screen_impl:
    path: ../feature/feature_main_screen_impl
  feature_message_preview_resolver:
    path: ../feature/feature_message_preview_resolver
  feature_message_preview_resolver_impl:
    path: ../feature/feature_message_preview_resolver_impl
  feature_notifications_settings_api:
    path: ../feature/feature_notifications_settings_api
  feature_notifications_settings_impl:
    path: ../feature/feature_notifications_settings_impl
  feature_privacy_settings_api:
    path: ../feature/feature_privacy_settings_api
  feature_privacy_settings_impl:
    path: ../feature/feature_privacy_settings_impl
  feature_profile_api:
    path: ../feature/feature_profile_api
  feature_profile_impl:
    path: ../feature/feature_profile_impl
  feature_settings_api:
    path: ../feature/feature_settings_api
  feature_settings_impl:
    path: ../feature/feature_settings_impl
  feature_settings_search_api:
    path: ../feature/feature_settings_search_api
  feature_settings_search_impl:
    path: ../feature/feature_settings_search_impl
  feature_shared_media_api:
    path: ../feature/feature_shared_media_api
  feature_shared_media_impl:
    path: ../feature/feature_shared_media_impl
  feature_stickers_api:
    path: ../feature/feature_stickers_api
  feature_stickers_impl:
    path: ../feature/feature_stickers_impl
  feature_wallpapers_api:
    path: ../feature/feature_wallpapers_api
  feature_wallpapers_impl:
    path: ../feature/feature_wallpapers_impl
  flutter:
    sdk: flutter
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 9e9f4e9beb08951b37ec8592147ba52979c33d30
  localization_api:
    path: ../localization_api
  localization_impl:
    path: ../localization_impl
  path_provider: ^2.0.1
  rxdart: ^0.26.0
  split_view:
    path: ../split_view
  td_client:
    path: ../td_client
  tg_theme:
    path: ../tg_theme

dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.1.2
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: c44f7871e6be360937b83b0e89be29c957dcdbd9
  tg_lint_rules:
    path: ../tg_lint_rules

flutter:
  assets:
    - assets/tdlib/config.txt