name: presentation
description: A new Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  jext:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jext
      ref: fc73e9fae90539ba0c4b03a531802ceb4547bcb6
  dart_numerics: ^0.0.5
  rxdart: ^0.26.0
  core:
    path: ../core
  coreui:
    path: ../coreui
  path_provider: ^2.0.1
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 02cb9197b758cd89457d71c2b4c1daab4d92477c
  td_client:
    path: ../td_client
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.4
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: a2e9b96e474656bfab70c51e9b903fc9e33b23d0
  analyzer: ^1.1.0
  build_runner: ^1.10.2
  flutter_test:
    sdk: flutter

flutter: