name: presentation
description: A new Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  feature_settings_search_api:
    path: ../feature/feature_settings_search_api
  feature_settings_search_impl:
    path: ../feature/feature_settings_search_impl
  localization_api:
    path: ../localization_api
  localization_impl:
    path: ../localization_impl
  split_view:
    path: ../split_view
  core_utils:
    path: ../core_utils
  core_tdlib_api:
    path: ../core_tdlib_api
  core_tdlib_impl:
    path: ../core_tdlib_impl
  feature_settings_api:
    path: ../feature/feature_settings_api
  feature_settings_impl:
    path: ../feature/feature_settings_impl
  feature_chat_impl:
    path: ../feature/feature_chat_impl
  feature_chat_api:
    path: ../feature/feature_chat_api
  feature_main_screen_api:
    path: ../feature/feature_main_screen_api
  feature_main_screen_impl:
    path: ../feature/feature_main_screen_impl
  feature_global_search_api:
    path: ../feature/feature_global_search_api
  feature_global_search_impl:
      path: ../feature/feature_global_search_impl
  feature_chats_list_api:
    path: ../feature/feature_chats_list_api
  feature_chats_list_impl:
    path: ../feature/feature_chats_list_impl
  jext:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jext
      ref: fc73e9fae90539ba0c4b03a531802ceb4547bcb6
  rxdart: ^0.26.0
  core:
    path: ../core
  coreui:
    path: ../coreui
  path_provider: ^2.0.1
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 02cb9197b758cd89457d71c2b4c1daab4d92477c
  td_client:
    path: ../td_client
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.4
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: ebf47e38b00f38c21aed7787f438202eeb847ef9
  analyzer: ^1.1.0
  build_runner: ^1.10.2
  flutter_test:
    sdk: flutter

flutter: