name: feature_profile_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  feature_chat_header_info_api:
    path: ../feature_chat_header_info_api
  feature_profile_api:
    path: ../feature_profile_api
  feature_shared_media_api:
    path: ../feature_shared_media_api
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  freezed_annotation: 1.1.0
  jugger: 2.0.0
  localization_api:
    path: ../../localization_api
  tuple: 2.0.0

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  freezed: 1.1.1
  jugger_generator: 2.1.0
  tg_lint_rules:
    path: ../../tg_lint_rules