name: localization_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  localization_api:
    path: ../localization_api
  sprintf: 6.0.0
  xml: 5.1.1

dev_dependencies:
  dependency_validator: 3.1.2
  tg_lint_rules:
    path: ../tg_lint_rules

flutter:
  assets:
    - assets/translations/en.xml