name: showcase
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  block_interaction_api:
    path: ../block_interaction_api
  chat_theme:
    path: ../feature/chat/chat_theme
  core_arch:
    path: ../core_arch
  core_arch_flutter:
    path: ../core_arch_flutter
  core_tdlib_api:
    path: ../core_tdlib_api
  core_utils:
    path: ../core_utils
  coreui:
    path: ../coreui
  dialog_api:
    path: ../dialog_api
  dialog_api_flutter:
    path: ../dialog_api_flutter
  fake:
    path: ../fake
  feature_auth_impl:
    path: ../feature/feature_auth_impl
  feature_chat_header_info_impl:
    path: ../feature/feature_chat_header_info_impl
  feature_chat_impl:
    path: ../feature/feature_chat_impl
  feature_chats_list_impl:
    path: ../feature/feature_chats_list_impl
  feature_country_api:
    path: ../feature/feature_country_api
  feature_country_impl:
    path: ../feature/feature_country_impl
  feature_create_new_chat_impl:
    path: ../feature/feature_create_new_chat_impl
  feature_file_api:
    path: ../feature/feature_file_api
  feature_message_preview_resolver:
    path: ../feature/feature_message_preview_resolver
  feature_message_preview_resolver_impl:
    path: ../feature/feature_message_preview_resolver_impl
  feature_profile_impl:
    path: ../feature/feature_profile_impl
  flutter:
    sdk: flutter
  freezed_annotation: 1.1.0
  intl: 0.17.0
  jugger: 2.0.0
  localization_api:
    path: ../localization_api
  localization_impl:
    path: ../localization_impl
  provider: 6.0.2
  provider_extensions:
    path: ../provider_extensions
  rxdart: 0.27.3
  split_view:
    path: ../split_view
  tg_theme:
    path: ../tg_theme
  tile:
    path: ../tile

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  freezed: 1.1.1
  jugger_generator: 2.1.0
  tg_lint_rules:
    path: ../tg_lint_rules