name: showcase
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  chat_theme:
    path: ../feature/chat/chat_theme
  core_arch:
    path: ../core_arch
  core_arch_flutter:
    path: ../core_arch_flutter
  core_tdlib_api:
    path: ../core_tdlib_api
  core_utils:
    path: ../core_utils
  coreui:
    path: ../coreui
  fake:
    path: ../fake
  feature_chat_header_info_impl:
    path: ../feature/feature_chat_header_info_impl
  feature_chat_impl:
    path: ../feature/feature_chat_impl
  feature_chats_list_impl:
    path: ../feature/feature_chats_list_impl
  feature_file_api:
    path: ../feature/feature_file_api
  feature_message_preview_resolver:
    path: ../feature/feature_message_preview_resolver
  feature_message_preview_resolver_impl:
    path: ../feature/feature_message_preview_resolver_impl
  feature_profile_impl:
    path: ../feature/feature_profile_impl
  flutter:
    sdk: flutter
  freezed_annotation: 1.1.0
  intl: ^0.17.0
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 9e9f4e9beb08951b37ec8592147ba52979c33d30
  localization_api:
    path: ../localization_api
  localization_impl:
    path: ../localization_impl
  provider: 6.0.0
  provider_extensions:
    path: ../provider_extensions
  rxdart: ^0.26.0
  split_view:
    path: ../split_view
  tg_theme:
    path: ../tg_theme
  tile:
    path: ../tile

dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.1.2
  freezed: ^1.1.1
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: c44f7871e6be360937b83b0e89be29c957dcdbd9
  tg_lint_rules:
    path: ../tg_lint_rules