name: feature_profile_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  chat_info:
    path: ../../chat/chat_info
  core_arch:
    path: ../../../core_arch
  core_arch_flutter:
    path: ../../../core_arch_flutter
  core_tdlib_api:
    path: ../../../core_tdlib_api
  coreui:
    path: ../../../coreui
  feature_chat_header_info_api:
    path: ../../feature_chat_header_info_api
  feature_profile_api:
    path: ../feature_profile_api
  feature_shared_media_api:
    path: ../../feature_shared_media_api
  flutter:
    sdk: flutter
  freezed_annotation: 1.1.0
  jugger: 2.1.0
  localization_api:
    path: ../../../localization_api
  provider_extensions:
    path: ../../../provider_extensions
  rxdart: 0.27.3
  tuple: 2.0.0
  user_info:
    path: ../../user/user_info

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  freezed: 1.1.1
  jugger_generator: 2.2.1
  tg_lint_rules:
    path: ../../../tg_lint_rules