name: dependencies_module_generator
homepage: https://github.com/ivk1800/jugger.dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: 4.7.0
  build: 2.3.0
  code_builder: 4.1.0
  dmg_annotation:
    path: ../dmg_annotation
  source_gen: 1.2.2

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../tg_lint_rules