name: feature_wallpapers_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_arch:
    path: ../../core_arch
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  feature_file_api:
    path: ../feature_file_api
  feature_wallpapers_api:
    path: ../feature_wallpapers_api
  flutter:
    sdk: flutter
  flutter_bloc: 7.2.0
  flutter_staggered_grid_view: ^0.4.0
  freezed_annotation: 0.14.2
  localization_api:
    path: ../../localization_api
  tile:
    path: ../../tile

dev_dependencies:
  build_runner: 2.1.1
  freezed: 0.14.2
  tg_lint_rules:
    path: ../../tg_lint_rules