name: feature_wallpapers_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  core_tdlib_api:
    path: ../../core_tdlib_api
  core_utils:
    path: ../../core_utils
  coreui:
    path: ../../coreui
  feature_file_api:
    path: ../feature_file_api
  feature_wallpapers_api:
    path: ../feature_wallpapers_api
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_staggered_grid_view: 0.4.0
  freezed_annotation: 1.1.0
  localization_api:
    path: ../../localization_api
  provider: 6.0.2
  shared_models:
    path: ../../shared/models
  td_api:
    path: ../../td/td_api
  tile:
    path: ../../tile

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  freezed: 1.1.1
  tg_lint_rules:
    path: ../../tg_lint_rules