name: feature_wallpapers_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  feature_file_api:
    path: ../feature_file_api
  flutter_staggered_grid_view: ^0.4.0
  core_arch:
    path: ../../core_arch
  core_tdlib_api:
    path: ../../core_tdlib_api
  localization_api:
    path: ../../localization_api
  provider: ^5.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.1
  feature_wallpapers_api:
    path: ../feature_wallpapers_api
  coreui:
    path: ../../coreui
  flutter:
    sdk: flutter

flutter: