name: td_api
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  tdlib:
    git:
      url: git@github.com:ivk1800/tdlib-dart.git
      ref: b25f5fa8a2541595ca68855a927eeb78e78f5f3b

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../tg_lint_rules