name: td_api
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  tdlib:
    git:
      url: git@github.com:ivk1800/tdlib-dart.git
      ref: e69061a264a666ad108e9bd4efeb8a2a0d28e6d9

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../tg_lint_rules