name: td_api
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  tdlib:
    git:
      url: git@github.com:ivk1800/tdlib-dart.git
      ref: 324fa2bd1f01213f803a5a747c50fe93f293bc62

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../tg_lint_rules