name: feature_contacts_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  chat_router_api:
    path: ../../../chat/chat_router_api
  core_arch:
    path: ../../../../core_arch
  core_tdlib_api:
    path: ../../../../core_tdlib_api
  feature_contacts_api:
    path: ../feature_contacts_api
  flutter:
    sdk: flutter
  jugger: 2.0.0
  localization_api:
    path: ../../../../localization_api
  provider_extensions:
    path: ../../../../provider_extensions

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.1.2
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: 5aa815deb32a55768f9901cd23c073d1672ca253
  tg_lint_rules:
    path: ../../../../tg_lint_rules