name: feature_chat_administration_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  async_utils:
    path: ../../../../async_utils
  block_interaction_api:
    path: ../../../../block_interaction_api
  chat_info:
    path: ../../chat_info
  core_arch:
    path: ../../../../core_arch
  core_arch_flutter:
    path: ../../../../core_arch_flutter
  core_tdlib_api:
    path: ../../../../core_tdlib_api
  coreui:
    path: ../../../../coreui
  dialog_api:
    path: ../../../../dialog_api
  error_transformer_api:
    path: ../../../../error_transformer_api
  feature_chat_administration_api:
    path: ../feature_chat_administration_api
  feature_chat_api:
    path: ../../../feature_chat_api
  flutter:
    sdk: flutter
  jugger: 2.1.0
  localization_api:
    path: ../../../../localization_api
  provider_extensions:
    path: ../../../../provider_extensions
  rxdart: 0.27.3

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  jugger_generator: 2.2.0
  tg_lint_rules:
    path: ../../../../tg_lint_rules