name: feature_auth_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  dialog_api:
    path: ../../dialog_api
  equatable: ^2.0.0
  feature_auth_api:
    path: ../feature_auth_api
  feature_country_api:
    path: ../feature_country_api
  flutter:
    sdk: flutter
  flutter_bloc: 7.2.0
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 9e9f4e9beb08951b37ec8592147ba52979c33d30
  localization_api:
    path: ../../localization_api
  mask_text_input_formatter: ^2.0.0
  rxdart: ^0.26.0

dev_dependencies:
  build_runner: ^2.1.7
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: c44f7871e6be360937b83b0e89be29c957dcdbd9
  tg_lint_rules:
    path: ../../tg_lint_rules