name: feature_auth_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  auth_manager_api:
    path: ../../component/auth_manager/auth_manager_api
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  dialog_api:
    path: ../../dialog_api
  equatable: ^2.0.0
  feature_auth_api:
    path: ../feature_auth_api
  feature_country_api:
    path: ../feature_country_api
  flutter:
    sdk: flutter
  flutter_bloc: 7.2.0
  jugger: ^2.0.0
  localization_api:
    path: ../../localization_api
  mask_text_input_formatter: ^2.0.0
  rxdart: ^0.26.0

dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.1.2
  jugger_generator: ^2.0.0
  tg_lint_rules:
    path: ../../tg_lint_rules