name: feature_auth_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  mask_text_input_formatter: ^2.0.0
  dialog_api:
    path: ../../dialog_api
  feature_country_api:
    path: ../feature_country_api
  coreui:
    path: ../../coreui
  core_tdlib_api:
    path: ../../core_tdlib_api
  localization_api:
    path: ../../localization_api
  provider: ^5.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.1
  rxdart: ^0.26.0
  feature_auth_api:
    path: ../feature_auth_api
  flutter:
    sdk: flutter
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 02cb9197b758cd89457d71c2b4c1daab4d92477c

dev_dependencies:
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: ebf47e38b00f38c21aed7787f438202eeb847ef9
  build_runner: ^1.10.2

flutter: