name: core_tdlib_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_tdlib_api:
    path: ../core_tdlib_api
  rxdart: ^0.26.0
  td_client:
    path: ../td_client

dev_dependencies:
  tg_lint_rules:
    path: ../tg_lint_rules