name: feature_chats_list_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  chat_router_api:
    path: ../chat/chat_router_api
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  core_utils:
    path: ../../core_utils
  coreui:
    path: ../../coreui
  feature_chats_list_api:
    path: ../feature_chats_list_api
  feature_message_preview_resolver:
    path: ../feature_message_preview_resolver
  flutter:
    sdk: flutter
  flutter_svg: 1.0.3
  jugger: 2.0.0
  localization_api:
    path: ../../localization_api
  provider_extensions:
    path: ../../provider_extensions
  queue:
    path: ../../queue
  shimmer: 2.0.0
  td_client:
    path: ../../td_client
  tile:
    path: ../../tile
  tuple: 2.0.0

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.1.2
  freezed: 1.1.1
  jugger_generator: 2.0.0
  tg_lint_rules:
    path: ../../tg_lint_rules