name: feature_chat_header_info_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  feature_chat_header_info_api:
    path: ../feature_chat_header_info_api
  flutter:
    sdk: flutter
  localization_api:
    path: ../../localization_api
  rxdart: ^0.26.0

dev_dependencies:
  dependency_validator: ^3.1.2
  tg_lint_rules:
    path: ../../tg_lint_rules