name: td_client
description: A new Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  tdlib:
    git:
      url: git@github.com:ivk1800/tdlib.git
      ref: 9888c49fe56090e2b956fb4cb64fce9af8c44aba
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: