name: td_client
description: A new Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  rxdart: ^0.26.0
  tdlib:
    git:
      url: git@github.com:ivk1800/tdlib.git
      ref: c64fe7a47969ea2491e154c27b645aa9a6a6f830
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: