name: td_client
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  rxdart: 0.27.3
  tdlib:
    git:
      url: git@github.com:ivk1800/tdlib-dart.git
      ref: ebe3a2a74edd15b7358ade6681276caa471b1815

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../tg_lint_rules