name: td_client
description: A new Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  rxdart: ^0.26.0
  tdlib:
    git:
      url: git@github.com:ivk1800/tdlib-dart.git
      ref: 2a29b25e4d6114ca67d72668f590bb4a5dae9c02
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: