name: feature_chat_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.17.0
  feature_message_preview_resolver:
    path: ../feature_message_preview_resolver
  localization_api:
    path: ../../localization_api
  provider: ^5.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.1
  path_provider: ^2.0.1
  flutter_svg: ^0.22.0
  coreui:
    path: ../../coreui
  core_utils:
    path: ../../core_utils
  core_tdlib_api:
    path: ../../core_tdlib_api
  feature_chat_api:
    path: ../feature_chat_api

  flutter:
    sdk: flutter

flutter: