name: feature_chat_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  chat_actions_panel:
    path: ../chat/chat_actions_panel
  chat_theme:
    path: ../chat/chat_theme
  core_arch:
    path: ../../core_arch
  core_tdlib_api:
    path: ../../core_tdlib_api
  core_utils:
    path: ../../core_utils
  coreui:
    path: ../../coreui
  dialog_api:
    path: ../../dialog_api
  equatable: ^2.0.0
  feature_chat_api:
    path: ../feature_chat_api
  feature_chat_header_info_api:
    path: ../feature_chat_header_info_api
  feature_message_preview_resolver:
    path: ../feature_message_preview_resolver
  flutter:
    sdk: flutter
  flutter_svg: 1.0.0
  freezed_annotation: 1.1.0
  intl: ^0.17.0
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 9e9f4e9beb08951b37ec8592147ba52979c33d30
  localization_api:
    path: ../../localization_api
  path_provider: ^2.0.1
  provider: 6.0.0
  rich_text_format:
    path: ../../rich_text/rich_text_format
  rich_text_format_flutter:
    path: ../../rich_text/rich_text_format_flutter
  tg_theme:
    path: ../../tg_theme
  tile:
    path: ../../tile

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: c44f7871e6be360937b83b0e89be29c957dcdbd9
  tg_lint_rules:
    path: ../../tg_lint_rules