name: feature_chat_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_arch:
    path: ../../core_arch
  core_tdlib_api:
    path: ../../core_tdlib_api
  core_utils:
    path: ../../core_utils
  coreui:
    path: ../../coreui
  feature_chat_api:
    path: ../feature_chat_api
  feature_chat_header_info_api:
    path: ../feature_chat_header_info_api
  feature_message_preview_resolver:
    path: ../feature_message_preview_resolver
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  freezed_annotation: 0.14.2
  intl: ^0.17.0
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 02cb9197b758cd89457d71c2b4c1daab4d92477c
  localization_api:
    path: ../../localization_api
  path_provider: ^2.0.1
  rich_text_format:
    path: ../../rich_text/rich_text_format
  rich_text_format_flutter:
    path: ../../rich_text/rich_text_format_flutter
  tile:
    path: ../../tile

dev_dependencies:
  build_runner: 2.1.1
  freezed: 0.14.2
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: 2351119ad514db2c2ffbe286677e91936c39ee61
  tg_lint_rules:
    path: ../../tg_lint_rules