name: fake
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  auth_manager_api:
    path: ../component/auth_manager/auth_manager_api
  contacts_manager_api:
    path: ../feature/contact/contacts_manager/contacts_manager_api
  core:
    path: ../core
  core_tdlib_api:
    path: ../core_tdlib_api
  error_transformer_api:
    path: ../error_transformer_api
  feature_chat_api:
    path: ../feature/feature_chat_api
  feature_chat_header_info_api:
    path: ../feature/feature_chat_header_info_api
  feature_file_api:
    path: ../feature/feature_file_api
  flutter:
    sdk: flutter
  localization_impl:
    path: ../localization_impl
  td_client:
    path: ../td_client
  username_generator: ^1.3.0

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../tg_lint_rules

flutter:
  assets:
    - assets/messages/
    - assets/users/