name: feature_chat_settings_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  feature_chat_settings_api:
    path: ../feature_chat_settings_api
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  freezed_annotation: 1.1.0
  localization_api:
    path: ../../localization_api

dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.1.2
  freezed: 1.1.1
  tg_lint_rules:
    path: ../../tg_lint_rules