name: demo
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  feature_chat_impl:
    path: ../feature/feature_chat_impl
  fake:
    path: ../fake
  coreui:
    path: ../coreui
  split_view:
    path: ../split_view
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: