name: folders_presentation
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  core_arch:
    path: ../../../core_arch
  dialog_api:
    path: ../../../dialog_api
  localization_api:
    path: ../../../localization_api

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../../tg_lint_rules