name: launch
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  app:
    path: ../app
  flutter:
    sdk: flutter
  showcase:
    path: ../showcase

dev_dependencies:
  dependency_validator: 3.1.2
  tg_lint_rules:
    path: ../tg_lint_rules

flutter:
  uses-material-design: true