name: error_transformer_td
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  error_transformer_api:
    path: ../error_transformer_api
  # todo: temporary
  td_client:
    path: ../td_client

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../tg_lint_rules