name: feature_country_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.0
  feature_country_api:
    path: ../feature_country_api
  flutter:
    sdk: flutter
  flutter_bloc: 7.2.0
  localization_api:
    path: ../../localization_api

dev_dependencies:
  dependency_validator: ^3.1.2
  tg_lint_rules:
    path: ../../tg_lint_rules

flutter:
  assets:
    - assets/countries.txt