name: feature_country_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  feature_country_api:
    path: ../feature_country_api
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  freezed_annotation: 1.1.0
  localization_api:
    path: ../../localization_api

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  freezed: 1.1.1
  tg_lint_rules:
    path: ../../tg_lint_rules

flutter:
  assets:
    - assets/countries.txt