name: dialog_api_flutter
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dialog_api:
    path: ../dialog_api
  flutter:
    sdk: flutter

dev_dependencies:
  tg_lint_rules:
    path: ../tg_lint_rules