name: auth_manager_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  auth_manager_api:
    path: ../auth_manager_api
  core_tdlib_impl:
    path: ../../../core_tdlib_impl

dev_dependencies:
  tg_lint_rules:
    path: ../../../tg_lint_rules