name: feature_settings_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../../core
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  feature_settings_api:
    path: ../feature_settings_api
  feature_settings_search_api:
    path: ../feature_settings_search_api
  flutter:
    sdk: flutter
  freezed_annotation: 1.1.0
  jugger: 2.0.0
  localization_api:
    path: ../../localization_api
  provider_extensions:
    path: ../../provider_extensions
  user_info:
    path: ../user/user_info

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  freezed: 1.1.1
  jugger_generator: 2.1.0
  tg_lint_rules:
    path: ../../tg_lint_rules