name: chat_actions_panel
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_tdlib_api:
    path: ../../../core_tdlib_api
  flutter:
    sdk: flutter
  freezed_annotation: 0.14.2
  rxdart: ^0.26.0

dev_dependencies:
  build_runner: 2.1.1
  freezed: 0.14.3
  tg_lint_rules:
    path: ../../../tg_lint_rules